#
# GitLab example CI/CD script
# See https://docs.gitlab.com/ee/ci/yaml/README.html
#
# Secure Variables like $DB_PASSWORD can added by going to your
# project’s Settings ➔ CI / CD ➔ Variables on the GitLab website.
#

stages:
  - build
  - test
  - deploy

# Set environment variables for folders in "cache" job settings
# for npm modules and Cypress binary
variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

# Cache using branch name
# https://gitlab.com/help/ci/caching/index.md
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - cache/Cypress
    - node_modules
    - dist

# Install NPM dependencies and Cypress
install:
  image: cypress/browsers:node14.17.0-chrome88-ff89
  stage: build

  script:
    - yarn install --frozen-lockfile
    # check Cypress binary path and cached versions
    - npx cypress cache path
    - npx cypress cache list
    # build in development mode, so we talk to the mock backend in our tests.
    - npm run build -- --configuration development

#
# Run Angular Karma unittests
#
unittests:
  image: volterrasystem/angular-e2e-testing:node12
  stage: test
  variables:
    NODE_ENV: development
  script:
    - npm run test
    # - npm run sonar
  only:
    - release

e2e-chrome:
  image: cypress/browsers:node14.17.0-chrome88-ff89
  stage: test
  script:
    - npm run start:mockapi &
    - npm run cypress:e2e
  only:
    - release

#
# Deploy to Heroku
# DPL is a deploy tool made for continuous deployment that’s developed and used
# by Travis CI, but can also be used with GitLab CI.
# https://docs.gitlab.com/ee/ci/examples/deployment/#using-dpl-with-docker
#
production:
  type: deploy
  stage: deploy
  image: ruby:latest
  script:
    # Get your key at https://dashboard.heroku.com/account
    # and add it to your project environment variables at GitLab.
    - echo "Heroku api key = $HEROKU_API_KEY"
    # The name of your app at Heroku. See https://dashboard.heroku.com/apps.
    - echo "Heroku appname = $HEROKU_APP_NAME"
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
  only:
    - master

#
# Example: Deploy to Google Firebase, as an alternative to Heroku
#
firebase:
  stage: deploy
  image: markhobson/node-chrome:latest
  before_script:
    - npm i --no-optional
    - npm i -g firebase-tools
  script:
    - npm run build
    - firebase deploy --token $FIREBASE_TOKEN
  only:
    # - master
    - firebase-branch
